In [1]:
import pandas as pd
import numpy as np 

pd.set_option('display.max_columns', 300)

## Step 1: Read in hold out data, scalers, and best model

In [2]:
df = pd.read_csv('movie_holdout_data.csv', index_col=0)
print(df.shape)
df.head()

(625, 28)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,gross
4551,Color,Eli Roth,285.0,100.0,0.0,389.0,Richard Burgi,640.0,Adventure|Horror,Daryl Sabara,The Green Inferno,21468,2082,Magda Apanowicz,0.0,activist|amazon|color in title|rain|rain forest,http://www.imdb.com/title/tt2403021/?ref_=fn_t...,164.0,English,USA,R,6000000.0,2013.0,550.0,5.4,2.35,12000,7186670.0
126,Color,Lana Wachowski,275.0,138.0,0.0,30.0,Daniel Bernhardt,234.0,Action|Sci-Fi,Steve Bastoni,The Matrix Reloaded,421818,534,Helmut Bakaitis,0.0,car motorcycle chase|one against many|oracle|p...,http://www.imdb.com/title/tt0234215/?ref_=fn_t...,2789.0,English,USA,R,150000000.0,2003.0,198.0,7.2,2.35,0,281492479.0
2251,Color,Todd Phillips,110.0,108.0,480.0,579.0,Sarah Silverman,970.0,Comedy,Jon Heder,School for Scoundrels,26100,4374,Jacinda Barrett,1.0,paintball|paintball gun|pepper spray|tennis|wh...,http://www.imdb.com/title/tt0462519/?ref_=fn_t...,97.0,English,USA,PG-13,20000000.0,2006.0,931.0,5.9,2.35,484,17803796.0
601,Color,Jonathan Liebesman,355.0,116.0,473.0,464.0,Jim Parrack,833.0,Action|Sci-Fi,Noel Fisher,Battle Los Angeles,154955,4001,Ramon Rodriguez,0.0,alien|extraterrestrial|invasion|marine|mission,http://www.imdb.com/title/tt1217613/?ref_=fn_t...,800.0,English,USA,PG-13,70000000.0,2011.0,697.0,5.8,2.35,25000,83552429.0
397,Color,George Miller,206.0,108.0,750.0,971.0,Hugh Jackman,49000.0,Animation|Comedy|Family|Music|Romance,Robin Williams,Happy Feet,132501,70996,Elizabeth Daily,0.0,dance|emperor penguin|friend|penguin|song,http://www.imdb.com/title/tt0366548/?ref_=fn_t...,548.0,English,USA,PG,100000000.0,2006.0,20000.0,6.5,2.35,0,197992827.0

In [3]:
import pickle

In [4]:
infile = open("model.pickle",'rb')
model = pickle.load(infile)
infile.close()

In [5]:
print(model.intercept_)
print(len(model.coef_))

-28651727.448831268
18

In [6]:
infile = open("other_info.pickle",'rb')
other_info = pickle.load(infile)
infile.close()

In [7]:
other_info

[{'G': 57937616.7, 'PG': 53613525.3, 'PG-13': 52682723.4, 'R': 25223942.9},
 2187.8671468587436,
 827.0320384461354,
 109.22168867547019,
 Index(['duration', 'director_facebook_likes', 'actor_3_facebook_likes',
        'actor_1_facebook_likes', 'cast_total_facebook_likes', 'budget',
        'actor_2_facebook_likes', 'yrs_old', 'superstar', 'content_rating_PG',
        'content_rating_PG-13', 'content_rating_R', 'color_Color',
        'actor_3_facebook_likes^2', 'PG_budget', 'PG13_budget', 'R_budget',
        'superstar_budget'],
       dtype='object')]

In [8]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,gross
4551,Color,Eli Roth,285.0,100.0,0.0,389.0,Richard Burgi,640.0,Adventure|Horror,Daryl Sabara,The Green Inferno,21468,2082,Magda Apanowicz,0.0,activist|amazon|color in title|rain|rain forest,http://www.imdb.com/title/tt2403021/?ref_=fn_t...,164.0,English,USA,R,6000000.0,2013.0,550.0,5.4,2.35,12000,7186670.0
126,Color,Lana Wachowski,275.0,138.0,0.0,30.0,Daniel Bernhardt,234.0,Action|Sci-Fi,Steve Bastoni,The Matrix Reloaded,421818,534,Helmut Bakaitis,0.0,car motorcycle chase|one against many|oracle|p...,http://www.imdb.com/title/tt0234215/?ref_=fn_t...,2789.0,English,USA,R,150000000.0,2003.0,198.0,7.2,2.35,0,281492479.0
2251,Color,Todd Phillips,110.0,108.0,480.0,579.0,Sarah Silverman,970.0,Comedy,Jon Heder,School for Scoundrels,26100,4374,Jacinda Barrett,1.0,paintball|paintball gun|pepper spray|tennis|wh...,http://www.imdb.com/title/tt0462519/?ref_=fn_t...,97.0,English,USA,PG-13,20000000.0,2006.0,931.0,5.9,2.35,484,17803796.0
601,Color,Jonathan Liebesman,355.0,116.0,473.0,464.0,Jim Parrack,833.0,Action|Sci-Fi,Noel Fisher,Battle Los Angeles,154955,4001,Ramon Rodriguez,0.0,alien|extraterrestrial|invasion|marine|mission,http://www.imdb.com/title/tt1217613/?ref_=fn_t...,800.0,English,USA,PG-13,70000000.0,2011.0,697.0,5.8,2.35,25000,83552429.0
397,Color,George Miller,206.0,108.0,750.0,971.0,Hugh Jackman,49000.0,Animation|Comedy|Family|Music|Romance,Robin Williams,Happy Feet,132501,70996,Elizabeth Daily,0.0,dance|emperor penguin|friend|penguin|song,http://www.imdb.com/title/tt0366548/?ref_=fn_t...,548.0,English,USA,PG,100000000.0,2006.0,20000.0,6.5,2.35,0,197992827.0

In [9]:
df.isna().mean()

color                        0.0000
director_name                0.0000
num_critic_for_reviews       0.0000
duration                     0.0000
director_facebook_likes      0.0000
actor_3_facebook_likes       0.0016
actor_2_name                 0.0000
actor_1_facebook_likes       0.0000
genres                       0.0000
actor_1_name                 0.0000
movie_title                  0.0000
num_voted_users              0.0000
cast_total_facebook_likes    0.0000
actor_3_name                 0.0016
facenumber_in_poster         0.0048
plot_keywords                0.0048
movie_imdb_link              0.0000
num_user_for_reviews         0.0000
language                     0.0000
country                      0.0000
content_rating               0.0000
budget                       0.0464
title_year                   0.0000
actor_2_facebook_likes       0.0000
imdb_score                   0.0000
aspect_ratio                 0.0144
movie_facebook_likes         0.0000
gross                        0.0000
dtype: float64

## Step 2: Feature Engineering for holdout set

Remember we have to perform the same transformations on our holdout data (feature engineering, extreme values, and scaling) that we performed on the original data.

In [10]:
df['actor_1_facebook_likes']= np.where(df['actor_1_facebook_likes'] >200000, 200000, df['actor_1_facebook_likes'])
df['actor_2_facebook_likes']= np.where(df['actor_2_facebook_likes'] >100000, 100000, df['actor_2_facebook_likes'])
df['cast_total_facebook_likes']= np.where(df['cast_total_facebook_likes'] >300000, 300000, df['cast_total_facebook_likes'])

In [11]:
other_info[0]

{'G': 57937616.7, 'PG': 53613525.3, 'PG-13': 52682723.4, 'R': 25223942.9}

In [12]:
budget_ratings = other_info[0]

In [13]:
df['budget'].fillna(df['content_rating'].map(budget_ratings), inplace=True)

In [14]:
act_3_mean =other_info[2]

In [15]:
df['actor_3_facebook_likes'].fillna(act_3_mean, inplace=True)

In [16]:
df['superstar'] = np.where(df['actor_1_facebook_likes']>=25000, 1, 0)

In [17]:
df = pd.get_dummies(df, columns=['content_rating', 'color'], drop_first=True)

In [18]:
df.head()

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,gross,superstar,content_rating_PG,content_rating_PG-13,content_rating_R,color_Color
4551,Eli Roth,285.0,100.0,0.0,389.0,Richard Burgi,640.0,Adventure|Horror,Daryl Sabara,The Green Inferno,21468,2082,Magda Apanowicz,0.0,activist|amazon|color in title|rain|rain forest,http://www.imdb.com/title/tt2403021/?ref_=fn_t...,164.0,English,USA,6000000.0,2013.0,550.0,5.4,2.35,12000,7186670.0,0,0,0,1,1
126,Lana Wachowski,275.0,138.0,0.0,30.0,Daniel Bernhardt,234.0,Action|Sci-Fi,Steve Bastoni,The Matrix Reloaded,421818,534,Helmut Bakaitis,0.0,car motorcycle chase|one against many|oracle|p...,http://www.imdb.com/title/tt0234215/?ref_=fn_t...,2789.0,English,USA,150000000.0,2003.0,198.0,7.2,2.35,0,281492479.0,0,0,0,1,1
2251,Todd Phillips,110.0,108.0,480.0,579.0,Sarah Silverman,970.0,Comedy,Jon Heder,School for Scoundrels,26100,4374,Jacinda Barrett,1.0,paintball|paintball gun|pepper spray|tennis|wh...,http://www.imdb.com/title/tt0462519/?ref_=fn_t...,97.0,English,USA,20000000.0,2006.0,931.0,5.9,2.35,484,17803796.0,0,0,1,0,1
601,Jonathan Liebesman,355.0,116.0,473.0,464.0,Jim Parrack,833.0,Action|Sci-Fi,Noel Fisher,Battle Los Angeles,154955,4001,Ramon Rodriguez,0.0,alien|extraterrestrial|invasion|marine|mission,http://www.imdb.com/title/tt1217613/?ref_=fn_t...,800.0,English,USA,70000000.0,2011.0,697.0,5.8,2.35,25000,83552429.0,0,0,1,0,1
397,George Miller,206.0,108.0,750.0,971.0,Hugh Jackman,49000.0,Animation|Comedy|Family|Music|Romance,Robin Williams,Happy Feet,132501,70996,Elizabeth Daily,0.0,dance|emperor penguin|friend|penguin|song,http://www.imdb.com/title/tt0366548/?ref_=fn_t...,548.0,English,USA,100000000.0,2006.0,20000.0,6.5,2.35,0,197992827.0,1,1,0,0,1

In [21]:
# your code here
df['budget^2']= df['budget']*df['budget']
df['actor_1_facebook_likes^2'] = df['actor_1_facebook_likes'] * df['actor_1_facebook_likes']   
df['actor_2_facebook_likes^2'] = df['actor_2_facebook_likes'] * df['actor_2_facebook_likes'] 
df['actor_3_facebook_likes^2'] = df['actor_3_facebook_likes'] * df['actor_3_facebook_likes'] 
df['cast_total_facebook_likes^2'] = df['cast_total_facebook_likes'] * df['cast_total_facebook_likes']

In [22]:
# your code here

df['cast_fb_budget'] = df['cast_total_facebook_likes'] *df['budget']
df['PG_budget'] = df['content_rating_PG'] *df['budget']
df['PG13_budget'] = df['content_rating_PG-13'] *df['budget']
df['R_budget'] = df['content_rating_R'] *df['budget']
df['superstar_budget'] = df['superstar'] *df['budget']
df['cast_fb_budget^2']= df['cast_total_facebook_likes'] *df['budget^2']

In [27]:
df['title_year']= pd.to_datetime(df['title_year'], format='%Y')
df['yrs_old']= 2016-  pd.DatetimeIndex(df['title_year']).year

## Step 3: Predict the holdout set

In [23]:
final_columns = list(other_info[4])

In [25]:
final_columns

['duration',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_1_facebook_likes',
 'cast_total_facebook_likes',
 'budget',
 'actor_2_facebook_likes',
 'yrs_old',
 'superstar',
 'content_rating_PG',
 'content_rating_PG-13',
 'content_rating_R',
 'color_Color',
 'actor_3_facebook_likes^2',
 'PG_budget',
 'PG13_budget',
 'R_budget',
 'superstar_budget']

In [28]:
df[final_columns]

,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,budget,actor_2_facebook_likes,yrs_old,superstar,content_rating_PG,content_rating_PG-13,content_rating_R,color_Color,actor_3_facebook_likes^2,PG_budget,PG13_budget,R_budget,superstar_budget
4551,100.0,0.0,389.0,640.0,2082,6000000.0,550.0,3,0,0,0,1,1,151321.0,0.0,0.0,6000000.0,0.0
126,138.0,0.0,30.0,234.0,534,150000000.0,198.0,13,0,0,0,1,1,900.0,0.0,0.0,150000000.0,0.0
2251,108.0,480.0,579.0,970.0,4374,20000000.0,931.0,10,0,0,1,0,1,335241.0,0.0,20000000.0,0.0,0.0
601,116.0,473.0,464.0,833.0,4001,70000000.0,697.0,5,0,0,1,0,1,215296.0,0.0,70000000.0,0.0,0.0
397,108.0,750.0,971.0,49000.0,70996,100000000.0,20000.0,10,1,1,0,0,1,942841.0,100000000.0,0.0,0.0,100000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4344,103.0,35.0,482.0,548.0,2389,1900000.0,495.0,13,0,0,1,0,1,232324.0,0.0,1900000.0,0.0,0.0
1952,95.0,0.0,98.0,11000.0,11994,25000000.0,876.0,14,0,0,0,1,1,9604.0,0.0,0.0,25000000.0,0.0
2442,112.0,0.0,177.0,805.0,1466,18000000.0,223.0,19,0,0,0,1,1,31329.0,0.0,0.0,18000000.0,0.0
2008,117.0,138.0,416.0,908.0,3204,25000000.0,581.0,6,0,0,0,1,1,173056.0,0.0,0.0,25000000.0,0.0
1891,108.0,425.0,766.0,20000.0,22739,25000000.0,962.0,5,0,0,0,1,1,586756.0,0.0,0.0,25000000.0,0.0

In [29]:
final_answers = model.predict(df[final_columns])

In [30]:
final_answers

array([ 7.00079318e+06,  1.20115931e+08,  3.56718534e+07,  8.15688512e+07,
        1.44499933e+08,  3.25525974e+07,  3.11372862e+07,  4.58568203e+07,
        6.75283150e+07,  8.09629529e+07,  5.83102322e+07,  3.17676201e+07,
        1.10999038e+06,  3.65865260e+08,  5.32118241e+06,  3.36501938e+07,
        7.03196743e+07,  4.07460898e+07,  1.41392788e+08,  3.73563759e+07,
        2.13459021e+08,  3.16571402e+07,  3.59326683e+07,  2.56647374e+07,
        3.62802818e+07,  1.73017434e+07,  5.57991826e+07,  2.60023790e+07,
        3.76029911e+07,  7.27424543e+07,  5.82965428e+07,  7.72679589e+07,
        3.70134342e+07,  3.97911271e+08,  2.12645207e+07,  5.53561984e+07,
        3.62638052e+07,  1.26569545e+07,  2.27516744e+06,  1.95991807e+08,
        2.43994737e+07,  6.82137347e+07,  3.05921521e+07,  9.01692161e+07,
        3.13302438e+07,  2.92251732e+07,  9.44108940e+07,  8.44981193e+07,
        3.03068247e+07,  2.11470011e+07,  1.69955674e+08,  2.87958383e+06,
        2.70504311e+08,  4.17650110e+07,  2.92161449e+07,  6.07015633e+07,
        2.55656525e+07,  1.97558696e+07,  5.32579125e+07,  4.42011154e+07,
        6.56255632e+07,  4.80440697e+06,  4.31904563e+07,  8.16528389e+07,
        3.41268847e+07,  1.24470597e+07,  4.46997710e+07,  2.46658813e+07,
        5.03616788e+07,  4.04686030e+07,  8.78978587e+07,  7.25196308e+07,
       -4.40155065e+06,  2.34525520e+07,  1.62237468e+05,  4.60652247e+07,
        6.05958933e+07,  7.16957353e+07,  2.97935261e+07,  3.33790189e+07,
        1.48709607e+07,  3.38883491e+07,  3.93514823e+07,  3.55212542e+07,
        7.07479749e+07,  5.95760179e+07,  1.00594781e+08,  3.06636571e+08,
        4.42034572e+07,  1.51981441e+07,  2.41908495e+07,  8.15353840e+07,
        2.42513553e+07,  5.70049160e+07,  1.51106211e+08,  1.08964244e+08,
        1.53409698e+08,  5.64535405e+07,  1.78740853e+08,  8.23917932e+07,
        8.56076664e+07,  3.02859543e+07,  2.24968660e+07,  2.51446489e+07,
        7.47483421e+07,  9.64550320e+06,  9.72206890e+07,  3.35134806e+07,
        8.79276885e+07,  3.91986924e+07,  2.16002911e+07,  2.27612515e+07,
        8.57498687e+07,  3.01230622e+07,  6.00164843e+07,  2.18404066e+08,
        4.21269988e+07,  5.08181804e+07,  7.00554073e+07,  3.81803826e+07,
        5.72201016e+07,  1.04096653e+07,  4.13794899e+07,  4.27269115e+07,
        1.65311754e+07,  9.27087384e+07,  2.34673034e+07,  4.28674699e+07,
        1.33091407e+08,  3.36231089e+07,  7.65149465e+07,  2.35291162e+07,
        5.66258712e+06,  2.70125063e+07,  3.20029620e+07,  2.87867070e+07,
        3.07839082e+07,  6.26485489e+07,  1.64234183e+08,  2.54637821e+07,
        2.69095902e+07,  3.56685787e+07,  1.86102631e+07,  3.89791362e+07,
        2.06592307e+07,  1.34897410e+07,  3.50924283e+07,  2.81358060e+07,
        1.65361823e+08,  2.46462895e+07,  9.37320024e+07,  1.49017105e+07,
        7.27451745e+07,  1.56994093e+07,  2.18552935e+07,  2.86606571e+07,
        8.31708714e+07,  1.72320780e+08,  1.94442889e+08,  6.04656175e+07,
        3.01160367e+07,  5.79619856e+07,  1.34316101e+08,  2.52223930e+07,
        2.31191652e+07,  1.57914463e+07,  7.54274464e+06,  1.86600002e+08,
        5.11821275e+07,  1.91988362e+07,  1.34181553e+08,  2.00316379e+07,
        1.40363480e+08,  4.96167573e+07,  5.72579852e+07,  3.05984317e+07,
        8.28332650e+07,  2.66931717e+07,  4.09703693e+07,  8.78106091e+06,
        9.17115029e+07,  1.61388359e+07,  2.99028365e+07,  6.20499396e+07,
        6.14925231e+07,  1.97079404e+07,  2.36372274e+06,  2.02076411e+07,
        8.21610232e+06,  2.62553754e+07,  9.95897779e+07,  1.24378827e+08,
        5.65445031e+07,  7.20183502e+07,  3.57409968e+07,  3.82231553e+07,
        1.65211312e+07,  5.76379938e+07,  1.35264473e+08,  3.53051869e+07,
        2.46643300e+07,  4.68972315e+07,  6.23137743e+07,  6.80912478e+07,
        2.34330238e+06,  1.55210060e+07,  9.96786750e+07,  1.61764445e+07,
        5.69792678e+07,  1.21673150e+08,  4.92057833e+07,  1.32212285e+08,
        5.48885459e+07,  6.31396271e+07,  2.50566453e+07,  1.99080721e+07,
        5.37038543e+07,  3.37479364e+07,  4.74159208e+07,  2.10999248e+07,
        5.45678808e+07,  2.76440148e+07,  5.15840778e+07,  4.21128369e+07,
        3.13027451e+07,  1.80819117e+08,  4.34682889e+07,  1.58284776e+07,
        1.48808262e+07,  7.13508167e+07,  4.26681764e+07,  6.01215862e+07,
        9.05202188e+07,  2.23480209e+07,  3.69285837e+07,  7.14480886e+07,
        1.53841914e+07,  2.72027458e+07,  1.24352011e+07,  1.00543351e+08,
        6.59470366e+07,  1.33841856e+08,  7.06356146e+06,  4.69672034e+07,
        5.86226826e+07,  1.41669559e+07,  3.25331583e+07,  5.30691919e+07,
        2.28918368e+07,  1.16493296e+07,  4.33406833e+07,  2.89322545e+07,
        4.67855490e+07,  4.34675771e+07,  2.46600783e+07,  1.89660392e+07,
        1.11605682e+08,  2.32806910e+07,  2.78266752e+07,  2.09735366e+08,
        5.75441131e+07,  4.03282021e+07,  1.79286702e+07,  2.12680173e+08,
        9.44482000e+07,  7.96699413e+07,  6.29415360e+07,  2.54325293e+07,
        3.86478345e+07,  3.49459415e+07,  2.89636939e+08,  5.48591736e+07,
        1.99199284e+07,  1.24842954e+08,  8.51073724e+07,  9.78870512e+07,
        6.30217415e+07,  3.92930999e+06,  7.11963422e+07,  3.92928391e+07,
        6.57771324e+07,  2.97946952e+07,  2.29432836e+07,  7.26303661e+06,
        7.26184716e+07,  8.50409378e+07,  9.31309066e+07,  8.14902423e+07,
        5.88450828e+07,  2.70489006e+07,  1.94017853e+07,  2.60941005e+08,
        5.99898774e+07,  5.15907863e+07,  3.87226113e+07,  1.11704407e+08,
        5.41293835e+07,  1.93754054e+07,  2.79333713e+07,  5.74736002e+07,
        1.22211085e+07,  6.90887190e+07,  3.19875955e+07,  4.33928649e+07,
        5.37038543e+07,  8.26515162e+07,  6.67329698e+07,  3.66511013e+07,
        3.05104730e+07,  5.83057870e+07,  4.59287199e+07,  1.25607630e+08,
        4.61159392e+07,  3.93079893e+06,  5.01011122e+07,  7.53324873e+07,
        3.18752179e+07,  6.73011999e+07,  5.80855138e+06,  2.37930734e+08,
        2.56307524e+07,  2.38479061e+06,  2.93678708e+07,  1.16452898e+08,
        9.28368672e+07,  4.80003205e+07,  8.62886583e+07,  5.85767746e+07,
        3.31968778e+07,  6.97157048e+07,  2.93939302e+07,  1.52496636e+08,
        3.06636571e+08,  5.57320584e+07,  1.01906428e+08,  3.60616129e+06,
        4.84197454e+07,  3.38612732e+07,  6.20083387e+06,  3.72081593e+07,
        1.18539004e+08,  1.02824204e+08,  3.91292723e+07,  7.08536128e+07,
        4.15733865e+07,  1.14583927e+07,  1.31677371e+08,  2.93046923e+07,
        4.96557753e+07,  1.10227845e+08,  5.39309439e+07,  1.14970699e+08,
        1.16887935e+08,  1.57016795e+08,  6.17575749e+06,  4.88536201e+07,
        2.24817066e+07,  7.25008127e+07,  2.65044199e+06,  6.25966281e+07,
        1.45013323e+07,  7.10374165e+07,  1.01213963e+07,  1.87351327e+07,
        1.75107194e+07,  4.54414536e+07,  1.84098742e+07,  3.23808483e+07,
        3.04416775e+08,  4.63557726e+07,  2.33459438e+07,  6.75099176e+07,
        6.05250801e+07,  5.58038684e+07,  5.03282124e+07,  1.22734346e+08,
        8.94113154e+07,  4.75260376e+07,  1.89497304e+07,  6.03084504e+07,
        1.85109955e+07,  3.26183944e+07,  2.24948875e+07,  2.00372202e+07,
        4.20377461e+07,  5.35222742e+07,  4.21455754e+07,  6.45963143e+07,
        7.68983360e+06,  7.25836643e+07,  2.69241668e+07,  2.48233763e+07,
        1.80093086e+08,  8.75739642e+07,  9.32906356e+07,  1.13444064e+08,
        2.20225823e+08,  4.99436836e+07,  5.93089903e+07,  3.10798141e+07,
        5.43831542e+07,  1.74188119e+07, -1.88087485e+06,  2.12349084e+07,
        1.21042037e+08,  5.40466441e+07,  8.68100182e+07,  1.44001805e+08,
        3.45679493e+07,  3.36156212e+07,  2.14015594e+07,  7.72281839e+07,
        5.24344862e+07,  3.98575156e+07,  2.21334216e+07,  1.38766482e+08,
        1.44054207e+08,  3.55994268e+07,  7.42627751e+07,  4.15346375e+07,
        2.26301827e+07,  3.69895828e+07,  4.85323520e+07,  3.95754351e+07,
        1.65885511e+07,  3.90690379e+07,  6.91353102e+07,  2.89565310e+07,
        7.14555075e+07,  5.92199714e+07,  3.18029239e+07,  1.20551690e+07,
        5.08900759e+07,  2.39170229e+07,  3.23202158e+07,  1.23092121e+07,
        3.49648676e+07,  1.94001567e+07,  2.15892618e+07,  1.18079638e+08,
        9.64033486e+07,  2.61182762e+07,  1.22003075e+07,  2.87475567e+07,
        5.75502639e+07,  1.56463564e+07,  1.44001805e+08,  2.12383985e+07,
        9.51182545e+07,  1.97514097e+07,  7.41259927e+07,  7.67576041e+07,
        4.74135326e+07,  3.91051821e+07,  4.60818659e+07,  4.49942695e+06,
        7.77497034e+07,  6.74090748e+07,  1.01671726e+07,  1.80541222e+07,
        6.70459656e+07,  3.99219796e+07,  7.77657778e+07,  6.85388123e+07,
        1.85529193e+07,  1.60756546e+07,  3.04649006e+08,  3.53295101e+07,
        3.77713374e+07,  7.43050848e+07,  6.07316002e+07,  1.85080472e+07,
        5.33985981e+07,  8.72901285e+07,  6.26847126e+07,  2.56710830e+07,
        4.75022510e+07,  4.75427208e+07,  8.68590967e+07,  2.33673667e+07,
        1.31589654e+07,  1.63353009e+07,  1.69411564e+08,  1.78740853e+08,
        9.96644024e+07,  1.84741901e+08,  8.14847482e+07,  2.15674704e+07,
        1.33607483e+08,  7.37790809e+06,  1.96236750e+07,  4.02925796e+07,
        1.79440971e+08,  4.39380349e+07,  3.28043902e+07,  3.33194528e+07,
        7.34947951e+07,  6.43215735e+07,  1.23844492e+08,  5.24885412e+07,
        1.16888604e+07,  9.06370382e+07,  1.30618675e+07,  1.82966309e+07,
        3.22921770e+07,  5.20209367e+07,  1.31317935e+07,  6.86302750e+07,
        2.52372242e+07,  8.38287235e+07,  1.07489182e+07,  2.02391177e+07,
        1.15877120e+08,  5.98237292e+06,  4.49695265e+07,  8.24539469e+07,
        7.07865006e+07,  3.22408578e+07,  5.05837281e+07,  6.85244570e+07,
        1.50831654e+07,  4.10277124e+07,  1.97438576e+07,  5.54414219e+07,
        2.37991045e+07,  5.93447578e+07,  3.84888887e+07,  5.40719277e+07,
        2.83694114e+07,  3.01699192e+07,  7.55868271e+06,  3.01403701e+07,
        8.32198318e+07,  1.51239555e+07,  9.50178032e+07,  3.82726931e+07,
        3.64172037e+07,  2.06771072e+07,  6.20251926e+07,  8.71164934e+07,
        1.33585036e+08,  9.20686053e+07,  1.74769560e+08,  3.20269301e+07,
        6.67546149e+07,  9.11456291e+06,  3.34764094e+06,  6.27848406e+06,
        3.91776731e+07,  7.85275218e+07,  1.37633598e+07,  4.47850560e+06,
        2.88001146e+07,  7.08935288e+07,  9.42710631e+07,  2.90306671e+07,
        2.55026236e+07,  7.36328938e+07,  4.94148268e+07,  2.43685476e+07,
        4.56184096e+07,  3.50208204e+07,  1.73904102e+08,  2.63628960e+07,
        4.78563745e+07,  4.48611318e+07,  1.65069038e+08,  1.69195986e+08,
        4.21876158e+07,  1.02182330e+07,  1.02258301e+08,  4.13285467e+07,
        3.13363795e+07,  2.22737833e+07,  1.13248560e+08,  5.86507587e+07,
        3.28277868e+07,  1.32424210e+08,  2.42991466e+07,  6.25699916e+07,
        1.51767370e+08,  4.52857015e+07,  3.30315214e+07,  1.65454261e+07,
        3.78757989e+07,  4.90553024e+07,  7.82389636e+07,  4.94151266e+07,
        3.15386279e+07,  3.44476313e+07,  8.74320885e+07,  3.41733648e+07,
        3.95653558e+07,  1.32602114e+07,  3.49135580e+07,  9.09029563e+05,
        4.34605865e+07,  5.05692699e+07,  1.65516664e+07,  5.62957306e+07,
        3.94288405e+07,  3.95276855e+07,  8.40788840e+07,  2.69984346e+07,
        6.11076197e+07,  7.01537766e+07,  2.61309919e+07,  2.60918233e+07,
        1.32067525e+08,  6.74085524e+07,  3.06759964e+07,  5.66585910e+07,
        1.29287840e+07,  1.32315887e+08,  2.77978456e+07,  9.54632137e+07,
        7.57095943e+07,  1.87718018e+07,  1.93622951e+07,  1.12601983e+07,
        1.63164576e+07,  2.36204785e+07,  3.13907231e+07,  2.93072376e+07,
        2.40031297e+07])

In [32]:
df_final = pd.DataFrame(final_answers)

## Step 4: Export your predictions

In [ ]:
df_final.to_csv('housing_preds_seanabu_wilson.csv')